CREATE SCHEMA webuser
    AUTHORIZATION postgres;

DROP TABLE WEBUSER.TB_SCHEDULING;
DROP TABLE WEBUSER.TB_ACTIVITIES;
DROP TABLE WEBUSER.TB_MEMBERS;
DROP TABLE WEBUSER.TB_PLANS;
DROP TABLE WEBUSER.TB_INSTRUCTORS;

CREATE TABLE WEBUSER.TB_INSTRUCTORS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    address TEXT,
    telephone VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_PLANS (
    id SERIAL PRIMARY KEY,
    plan VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.TB_MEMBERS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    address TEXT,
    telephone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    plan_type INTEGER REFERENCES WEBUSER.TB_PLANS(id),
    start_date DATE NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_ACTIVITIES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    instructor INTEGER REFERENCES WEBUSER.TB_INSTRUCTORS(id) ON DELETE CASCADE,
    date TIMESTAMP NOT NULL,
    duration INT NOT NULL,
    capacity INT NOT NULL,
    plan_type INT REFERENCES WEBUSER.TB_PLANS(id),
    active BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.TB_SCHEDULING (
    id SERIAL PRIMARY KEY,
    activity INTEGER REFERENCES WEBUSER.TB_ACTIVITIES(id) ON DELETE CASCADE,
    member INTEGER REFERENCES WEBUSER.TB_MEMBERS(id) ON DELETE CASCADE
);
